import {createRouter,createWebHashHistory} from 'vue-router'

const router=createRouter({
    history:createWebHashHistory(),
    routes:[
        {
            path:"/",
            redirect:"/home"
        },
        {
            path:"/home",
            component:()=>import("@/views/home/home.vue")
        },
        {
            path:"/favor",
            component:()=>import("@/views/favor/favor.vue")
        },
        {
            path:"/order",
            component:()=>import("@/views/order/order.vue")
        }
        ,
        {
            path:"/profile",
            component:()=>import("@/views/profile/profile.vue"),
            meta:{
                hideTabBar:true
            }
        }
        ,
        {
            path:"/city",
            component:()=>import("@/views/city/city.vue"),
            meta:{
                hideTabBar:true
            }
        },
        {
            path:"/search",
            component:()=>import("@/views/search/search.vue"),
            meta:{
                hideTabBar:true
            }
        },
        {
            path:"/detail/:houseId",
            component:()=>import("@/views/detail/detail.vue"),
            meta:{
                hideTabBar:true
            }
        }
    ]
})
export default router